AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  feedly-cli 

  Add a url to your Feedly account
  
Metadata:
  AWS::ServerlessRepo::Application:
    Name: feedly-cli 
    Author: martijngastkemper 
    Description: Add a url to your Feedly account

Globals:
  Function:
    KmsKeyArn: !GetAtt KMSKey.Arn
    Environment:
      Variables:
          FEEDLY_ACCESS_KEY: !GetAtt FeedlyAccessKey.Value
          SENTRY_DSN: !GetAtt SentryDSN.Value
          SLACK_FEEDLY_USAGE: !GetAtt SlackFeedlyUsage.Value

Resources:

  FeedlyCliFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambdaHandler
      Runtime: nodejs8.10
      Events:
        Status:
            Type: Api
            Properties:
                Path: /status
                Method: get

        Labels:
          Type: Api 
          Properties:
            Path: /labels
            Method: get

        ReadLater:
            Type: Api
            Properties:
                Path: /read-later
                Method: post


  KMSKey:
     Type: AWS::KMS::Key
     Properties:
       KeyPolicy:
         Id: "FeedlyCli"
         Statement:
            - 
               Sid: "Allow administration of the key"
               Effect: "Allow"
               Action:
                 - "kms:Create*"
                 - "kms:Describe*"
                 - "kms:Enable*"
                 - "kms:List*"
                 - "kms:Put*"
                 - "kms:Update*"
                 - "kms:Revoke*"
                 - "kms:Disable*"
                 - "kms:Get*"
                 - "kms:Delete*"
                 - "kms:ScheduleKeyDeletion"
                 - "kms:CancelKeyDeletion"
                 - "kms:Decrypt"
                 - "kms:Encrypt"
               Principal:
                 AWS: !Ref AWS::AccountId
               Resource: '*'

  SentryDSN:
     Type: AWS::SSM::Parameter
     Properties:
        Type: "String"
        Value: "dummy-value"
        Description: "Feedly-cli Sentry DSN"

  FeedlyAccessKey:
      Type: AWS::SSM::Parameter
      Properties:
          Type: "String"
          Value: "dummy-value"
          Description: "Feedly-cli Feedly Access Key"

  SlackFeedlyUsage:
      Type: AWS::SSM::Parameter
      Properties:
          Type: "String"
          Value: "dummy-value"
          Description: "Post message to Slack with Feedly API usage stats"
